// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: calculator.proto

#ifndef PROTOBUF_INCLUDED_calculator_2eproto
#define PROTOBUF_INCLUDED_calculator_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_calculator_2eproto 

namespace protobuf_calculator_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[2];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_calculator_2eproto
namespace calculator {
class InputNumber;
class InputNumberDefaultTypeInternal;
extern InputNumberDefaultTypeInternal _InputNumber_default_instance_;
class OutputNumber;
class OutputNumberDefaultTypeInternal;
extern OutputNumberDefaultTypeInternal _OutputNumber_default_instance_;
}  // namespace calculator
namespace google {
namespace protobuf {
template<> ::calculator::InputNumber* Arena::CreateMaybeMessage<::calculator::InputNumber>(Arena*);
template<> ::calculator::OutputNumber* Arena::CreateMaybeMessage<::calculator::OutputNumber>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace calculator {

// ===================================================================

class InputNumber : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:calculator.InputNumber) */ {
 public:
  InputNumber();
  virtual ~InputNumber();

  InputNumber(const InputNumber& from);

  inline InputNumber& operator=(const InputNumber& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  InputNumber(InputNumber&& from) noexcept
    : InputNumber() {
    *this = ::std::move(from);
  }

  inline InputNumber& operator=(InputNumber&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const InputNumber& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const InputNumber* internal_default_instance() {
    return reinterpret_cast<const InputNumber*>(
               &_InputNumber_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(InputNumber* other);
  friend void swap(InputNumber& a, InputNumber& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline InputNumber* New() const final {
    return CreateMaybeMessage<InputNumber>(NULL);
  }

  InputNumber* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<InputNumber>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const InputNumber& from);
  void MergeFrom(const InputNumber& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(InputNumber* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // int32 num1 = 1;
  void clear_num1();
  static const int kNum1FieldNumber = 1;
  ::google::protobuf::int32 num1() const;
  void set_num1(::google::protobuf::int32 value);

  // int32 num2 = 2;
  void clear_num2();
  static const int kNum2FieldNumber = 2;
  ::google::protobuf::int32 num2() const;
  void set_num2(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:calculator.InputNumber)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int32 num1_;
  ::google::protobuf::int32 num2_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_calculator_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class OutputNumber : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:calculator.OutputNumber) */ {
 public:
  OutputNumber();
  virtual ~OutputNumber();

  OutputNumber(const OutputNumber& from);

  inline OutputNumber& operator=(const OutputNumber& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  OutputNumber(OutputNumber&& from) noexcept
    : OutputNumber() {
    *this = ::std::move(from);
  }

  inline OutputNumber& operator=(OutputNumber&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const OutputNumber& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const OutputNumber* internal_default_instance() {
    return reinterpret_cast<const OutputNumber*>(
               &_OutputNumber_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(OutputNumber* other);
  friend void swap(OutputNumber& a, OutputNumber& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline OutputNumber* New() const final {
    return CreateMaybeMessage<OutputNumber>(NULL);
  }

  OutputNumber* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<OutputNumber>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const OutputNumber& from);
  void MergeFrom(const OutputNumber& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(OutputNumber* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // int32 num = 1;
  void clear_num();
  static const int kNumFieldNumber = 1;
  ::google::protobuf::int32 num() const;
  void set_num(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:calculator.OutputNumber)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int32 num_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_calculator_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// InputNumber

// int32 num1 = 1;
inline void InputNumber::clear_num1() {
  num1_ = 0;
}
inline ::google::protobuf::int32 InputNumber::num1() const {
  // @@protoc_insertion_point(field_get:calculator.InputNumber.num1)
  return num1_;
}
inline void InputNumber::set_num1(::google::protobuf::int32 value) {
  
  num1_ = value;
  // @@protoc_insertion_point(field_set:calculator.InputNumber.num1)
}

// int32 num2 = 2;
inline void InputNumber::clear_num2() {
  num2_ = 0;
}
inline ::google::protobuf::int32 InputNumber::num2() const {
  // @@protoc_insertion_point(field_get:calculator.InputNumber.num2)
  return num2_;
}
inline void InputNumber::set_num2(::google::protobuf::int32 value) {
  
  num2_ = value;
  // @@protoc_insertion_point(field_set:calculator.InputNumber.num2)
}

// -------------------------------------------------------------------

// OutputNumber

// int32 num = 1;
inline void OutputNumber::clear_num() {
  num_ = 0;
}
inline ::google::protobuf::int32 OutputNumber::num() const {
  // @@protoc_insertion_point(field_get:calculator.OutputNumber.num)
  return num_;
}
inline void OutputNumber::set_num(::google::protobuf::int32 value) {
  
  num_ = value;
  // @@protoc_insertion_point(field_set:calculator.OutputNumber.num)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace calculator

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_calculator_2eproto
