// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: calculator.proto

#include "calculator.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace calculator {
class InputNumberDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<InputNumber>
      _instance;
} _InputNumber_default_instance_;
class OutputNumberDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<OutputNumber>
      _instance;
} _OutputNumber_default_instance_;
}  // namespace calculator
namespace protobuf_calculator_2eproto {
static void InitDefaultsInputNumber() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::calculator::_InputNumber_default_instance_;
    new (ptr) ::calculator::InputNumber();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::calculator::InputNumber::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_InputNumber =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsInputNumber}, {}};

static void InitDefaultsOutputNumber() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::calculator::_OutputNumber_default_instance_;
    new (ptr) ::calculator::OutputNumber();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::calculator::OutputNumber::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_OutputNumber =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsOutputNumber}, {}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_InputNumber.base);
  ::google::protobuf::internal::InitSCC(&scc_info_OutputNumber.base);
}

::google::protobuf::Metadata file_level_metadata[2];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::calculator::InputNumber, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::calculator::InputNumber, num1_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::calculator::InputNumber, num2_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::calculator::OutputNumber, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::calculator::OutputNumber, num_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::calculator::InputNumber)},
  { 7, -1, sizeof(::calculator::OutputNumber)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::calculator::_InputNumber_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::calculator::_OutputNumber_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "calculator.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 2);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\020calculator.proto\022\ncalculator\")\n\013InputN"
      "umber\022\014\n\004num1\030\001 \001(\005\022\014\n\004num2\030\002 \001(\005\"\033\n\014Out"
      "putNumber\022\013\n\003num\030\001 \001(\0052\220\002\n\nCalculator\022\?\n"
      "\010Addition\022\027.calculator.InputNumber\032\030.cal"
      "culator.OutputNumber\"\000\022A\n\nSubraction\022\027.c"
      "alculator.InputNumber\032\030.calculator.Outpu"
      "tNumber\"\000\022\?\n\010Multiply\022\027.calculator.Input"
      "Number\032\030.calculator.OutputNumber\"\000\022=\n\006Di"
      "vide\022\027.calculator.InputNumber\032\030.calculat"
      "or.OutputNumber\"\000b\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 385);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "calculator.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_calculator_2eproto
namespace calculator {

// ===================================================================

void InputNumber::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int InputNumber::kNum1FieldNumber;
const int InputNumber::kNum2FieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

InputNumber::InputNumber()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_calculator_2eproto::scc_info_InputNumber.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:calculator.InputNumber)
}
InputNumber::InputNumber(const InputNumber& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&num1_, &from.num1_,
    static_cast<size_t>(reinterpret_cast<char*>(&num2_) -
    reinterpret_cast<char*>(&num1_)) + sizeof(num2_));
  // @@protoc_insertion_point(copy_constructor:calculator.InputNumber)
}

void InputNumber::SharedCtor() {
  ::memset(&num1_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&num2_) -
      reinterpret_cast<char*>(&num1_)) + sizeof(num2_));
}

InputNumber::~InputNumber() {
  // @@protoc_insertion_point(destructor:calculator.InputNumber)
  SharedDtor();
}

void InputNumber::SharedDtor() {
}

void InputNumber::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* InputNumber::descriptor() {
  ::protobuf_calculator_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_calculator_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const InputNumber& InputNumber::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_calculator_2eproto::scc_info_InputNumber.base);
  return *internal_default_instance();
}


void InputNumber::Clear() {
// @@protoc_insertion_point(message_clear_start:calculator.InputNumber)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&num1_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&num2_) -
      reinterpret_cast<char*>(&num1_)) + sizeof(num2_));
  _internal_metadata_.Clear();
}

bool InputNumber::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:calculator.InputNumber)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int32 num1 = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &num1_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 num2 = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &num2_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:calculator.InputNumber)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:calculator.InputNumber)
  return false;
#undef DO_
}

void InputNumber::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:calculator.InputNumber)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 num1 = 1;
  if (this->num1() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->num1(), output);
  }

  // int32 num2 = 2;
  if (this->num2() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->num2(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:calculator.InputNumber)
}

::google::protobuf::uint8* InputNumber::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:calculator.InputNumber)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 num1 = 1;
  if (this->num1() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->num1(), target);
  }

  // int32 num2 = 2;
  if (this->num2() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->num2(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:calculator.InputNumber)
  return target;
}

size_t InputNumber::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:calculator.InputNumber)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // int32 num1 = 1;
  if (this->num1() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->num1());
  }

  // int32 num2 = 2;
  if (this->num2() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->num2());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void InputNumber::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:calculator.InputNumber)
  GOOGLE_DCHECK_NE(&from, this);
  const InputNumber* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const InputNumber>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:calculator.InputNumber)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:calculator.InputNumber)
    MergeFrom(*source);
  }
}

void InputNumber::MergeFrom(const InputNumber& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:calculator.InputNumber)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.num1() != 0) {
    set_num1(from.num1());
  }
  if (from.num2() != 0) {
    set_num2(from.num2());
  }
}

void InputNumber::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:calculator.InputNumber)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void InputNumber::CopyFrom(const InputNumber& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:calculator.InputNumber)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool InputNumber::IsInitialized() const {
  return true;
}

void InputNumber::Swap(InputNumber* other) {
  if (other == this) return;
  InternalSwap(other);
}
void InputNumber::InternalSwap(InputNumber* other) {
  using std::swap;
  swap(num1_, other->num1_);
  swap(num2_, other->num2_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata InputNumber::GetMetadata() const {
  protobuf_calculator_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_calculator_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void OutputNumber::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int OutputNumber::kNumFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

OutputNumber::OutputNumber()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_calculator_2eproto::scc_info_OutputNumber.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:calculator.OutputNumber)
}
OutputNumber::OutputNumber(const OutputNumber& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  num_ = from.num_;
  // @@protoc_insertion_point(copy_constructor:calculator.OutputNumber)
}

void OutputNumber::SharedCtor() {
  num_ = 0;
}

OutputNumber::~OutputNumber() {
  // @@protoc_insertion_point(destructor:calculator.OutputNumber)
  SharedDtor();
}

void OutputNumber::SharedDtor() {
}

void OutputNumber::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* OutputNumber::descriptor() {
  ::protobuf_calculator_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_calculator_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const OutputNumber& OutputNumber::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_calculator_2eproto::scc_info_OutputNumber.base);
  return *internal_default_instance();
}


void OutputNumber::Clear() {
// @@protoc_insertion_point(message_clear_start:calculator.OutputNumber)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  num_ = 0;
  _internal_metadata_.Clear();
}

bool OutputNumber::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:calculator.OutputNumber)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int32 num = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &num_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:calculator.OutputNumber)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:calculator.OutputNumber)
  return false;
#undef DO_
}

void OutputNumber::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:calculator.OutputNumber)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 num = 1;
  if (this->num() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->num(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:calculator.OutputNumber)
}

::google::protobuf::uint8* OutputNumber::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:calculator.OutputNumber)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 num = 1;
  if (this->num() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->num(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:calculator.OutputNumber)
  return target;
}

size_t OutputNumber::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:calculator.OutputNumber)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // int32 num = 1;
  if (this->num() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->num());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void OutputNumber::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:calculator.OutputNumber)
  GOOGLE_DCHECK_NE(&from, this);
  const OutputNumber* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const OutputNumber>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:calculator.OutputNumber)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:calculator.OutputNumber)
    MergeFrom(*source);
  }
}

void OutputNumber::MergeFrom(const OutputNumber& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:calculator.OutputNumber)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.num() != 0) {
    set_num(from.num());
  }
}

void OutputNumber::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:calculator.OutputNumber)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void OutputNumber::CopyFrom(const OutputNumber& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:calculator.OutputNumber)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool OutputNumber::IsInitialized() const {
  return true;
}

void OutputNumber::Swap(OutputNumber* other) {
  if (other == this) return;
  InternalSwap(other);
}
void OutputNumber::InternalSwap(OutputNumber* other) {
  using std::swap;
  swap(num_, other->num_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata OutputNumber::GetMetadata() const {
  protobuf_calculator_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_calculator_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace calculator
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::calculator::InputNumber* Arena::CreateMaybeMessage< ::calculator::InputNumber >(Arena* arena) {
  return Arena::CreateInternal< ::calculator::InputNumber >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::calculator::OutputNumber* Arena::CreateMaybeMessage< ::calculator::OutputNumber >(Arena* arena) {
  return Arena::CreateInternal< ::calculator::OutputNumber >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
